name: Setup
description: Setup Node.js and install dependencies

inputs:
  npm-token:
    description: NPM token for private registry authentication
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
        registry-url: 'https://registry.npmjs.org'

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: node-modules-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
